### ISSUE TITLE
Website overzet checklist

### ISSUE THREAD

**Issue by Duncank** [Duncank/5X#84]
- [ ] Boerderijtje op de Veluwe; prijzenitem veranderen in regelhandler
- [x] Untopa; datumfilter mogelijk maken
- [x] Untopa; custom factuurmails
- [x] Untopa; inschrijvinginfo in float editpane?
- [x] Is de mail-taal hier al gefixt voor standaard NL?
- [x] Checkboxes checken:
	    "zichtbaar_in_headlines" => "Zichtbaar in headlines",
	    "zichtbaar_op_homepage" => "Zichtbaar op homepage",
	    "geen_verzendkosten" => "Geen verzendkosten",
	    "uitverkocht" => "Uitverkocht",
	    "combineerbaar" => "Combineerbaar (verzending)"
	);
